nix/ratman: work around webui cross-compilation issues
There's an upstream nixpkgs issue, which breaks eg. `pkgsStatic.yarn2nix`:
https://github.com/NixOS/nixpkgs/issues/116207

Thankfully, the output of `ratman-webui` is a pile of arch-independent,
static assets, so we don't actually need this to work; we only need the
build scripts to run on the builder.

--------------------------------------------------------------------------

> $ nix-shell -p pkgsStatic.yarn2nix
> error: attribute 'runtimeShell' missing
>
>        at /home/embr/src/nixpkgs/pkgs/top-level/all-packages.nix:731:17:
>
>           730|       substitutions = {
>           731|         shell = targetPackages.runtimeShell;
>              |                 ^
>           732|         passthru.tests = tests.makeWrapper;
> (use '--show-trace' to show detailed location information)